"""remove_start_end_index_contractor_speaker_from_feedbacks

Revision ID: 2164d47fca79
Revises: a902fbcdb69e
Create Date: 2026-07-30 11:27:56.127675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2164d47fca79'
down_revision: Union[str, None] = 'a902fbcdb69e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedbacks', 'speaker_name')
    op.drop_column('feedbacks', 'contractor_profile')
    op.drop_column('feedbacks', 'start_index')
    op.drop_column('feedbacks', 'end_index')
    op.add_column('file_details', sa.Column('rfmm_cluster', sa.String(length=100), nullable=True))
    op.drop_index('ix_file_details_rbdm_cluster', table_name='file_details')
    op.create_index(op.f('ix_file_details_rfmm_cluster'), 'file_details', ['rfmm_cluster'], unique=False)
    op.drop_column('file_details', 'rbdm_cluster')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_details', sa.Column('rbdm_cluster', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_file_details_rfmm_cluster'), table_name='file_details')
    op.create_index('ix_file_details_rbdm_cluster', 'file_details', ['rbdm_cluster'], unique=False)
    op.drop_column('file_details', 'rfmm_cluster')
    op.add_column('feedbacks', sa.Column('end_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('start_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('contractor_profile', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('speaker_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
