"""remove category and brand and description

Revision ID: 244b9d77cc00
Revises: c25e8eb82568
Create Date: 2026-07-20 16:19:26.963344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244b9d77cc00'
down_revision: Union[str, None] = 'c25e8eb82568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('products_brand_id_fkey', 'products', type_='foreignkey')
    op.drop_constraint('products_category_id_fkey', 'products', type_='foreignkey')
    op.drop_column('products', 'brand_id')
    op.drop_column('products', 'category_id')
    op.drop_column('products', 'description')
    op.drop_table('product_brands')
    op.drop_table('product_categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('brand_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('products_category_id_fkey', 'products', 'product_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('products_brand_id_fkey', 'products', 'product_brands', ['brand_id'], ['id'], ondelete='CASCADE')
    op.create_table('product_brands',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name='product_brands_category_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='product_brands_pkey'),
    sa.UniqueConstraint('name', name='product_brands_name_key')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='product_categories_pkey'),
    sa.UniqueConstraint('name', name='product_categories_name_key')
    )
    # ### end Alembic commands ###
