"""change_product_id_to_integer

Revision ID: 2fe470ce7506
Revises: c5f73497ace3
Create Date: 2026-07-21 13:19:49.696030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe470ce7506'
down_revision: Union[str, None] = 'c5f73497ace3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing foreign key and columns
    op.drop_constraint('feedbacks_product_id_fkey', 'feedbacks', type_='foreignkey')
    op.execute("ALTER TABLE feedbacks DROP COLUMN product_id")
    op.execute("ALTER TABLE products DROP COLUMN id CASCADE")
    
    # Recreate as SERIAL/Integer
    op.execute("ALTER TABLE products ADD COLUMN id SERIAL PRIMARY KEY")
    op.execute("ALTER TABLE feedbacks ADD COLUMN product_id INTEGER REFERENCES products(id)")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('feedbacks', 'product_id',
               existing_type=sa.Integer(),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
