"""Sync models to DB

Revision ID: 4f9ea1944e26
Revises: a3f1b2c4d5e6
Create Date: 2026-07-17 14:40:42.311577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f9ea1944e26'
down_revision: Union[str, None] = 'a3f1b2c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_tag_link',
    sa.Column('feedback_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tag_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['feedback_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feedback_id', 'tag_id')
    )
    op.drop_table('job_summaries')
    op.add_column('feedback_tags', sa.Column('sub_tag_name', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'feedback_tags', ['tag_name'])
    op.drop_constraint('feedback_tags_category_id_fkey', 'feedback_tags', type_='foreignkey')
    op.drop_column('feedback_tags', 'description')
    op.drop_column('feedback_tags', 'category_id')
    op.add_column('feedbacks', sa.Column('group_type', sa.String(length=100), nullable=False))
    op.add_column('feedbacks', sa.Column('category_type', sa.String(length=100), nullable=True))
    op.add_column('feedbacks', sa.Column('ai_summary', sa.Text(), nullable=False))
    op.drop_constraint('feedbacks_tag_id_fkey', 'feedbacks', type_='foreignkey')
    op.drop_constraint('feedbacks_category_id_fkey', 'feedbacks', type_='foreignkey')
    op.drop_table('feedback_categories')
    op.drop_column('feedbacks', 'remarks')
    op.drop_column('feedbacks', 'tag_id')
    op.drop_column('feedbacks', 'sentiment_label')
    op.drop_column('feedbacks', 'category_id')
    op.drop_column('feedbacks', 'sentiment_score')
    op.add_column('file_details', sa.Column('call_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('file_details', sa.Column('audio_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('file_details', sa.Column('language_code', sa.String(length=20), nullable=True))
    op.add_column('file_details', sa.Column('state', sa.String(length=100), nullable=True))
    op.add_column('file_details', sa.Column('user_id_metadata', sa.String(length=100), nullable=True))
    op.drop_index('ix_file_details_user_id', table_name='file_details')
    op.create_index(op.f('ix_file_details_call_date'), 'file_details', ['call_date'], unique=False)
    op.create_index(op.f('ix_file_details_language_code'), 'file_details', ['language_code'], unique=False)
    op.create_index(op.f('ix_file_details_state'), 'file_details', ['state'], unique=False)
    op.create_index(op.f('ix_file_details_user_id_metadata'), 'file_details', ['user_id_metadata'], unique=False)
    op.drop_column('file_details', 'user_id')
    op.add_column('processed_file', sa.Column('insights_raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('processed_file', 'normalized_text')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.add_column('processed_file', sa.Column('normalized_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('processed_file', 'insights_raw_json')
    op.add_column('file_details', sa.Column('user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_file_details_user_id_metadata'), table_name='file_details')
    op.drop_index(op.f('ix_file_details_state'), table_name='file_details')
    op.drop_index(op.f('ix_file_details_language_code'), table_name='file_details')
    op.drop_index(op.f('ix_file_details_call_date'), table_name='file_details')
    op.create_index('ix_file_details_user_id', 'file_details', ['user_id'], unique=False)
    op.drop_column('file_details', 'user_id_metadata')
    op.drop_column('file_details', 'state')
    op.drop_column('file_details', 'language_code')
    op.drop_column('file_details', 'audio_duration_seconds')
    op.drop_column('file_details', 'call_date')
    op.add_column('feedbacks', sa.Column('sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('sentiment_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('feedbacks', sa.Column('remarks', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('feedbacks_category_id_fkey', 'feedbacks', 'feedback_categories', ['category_id'], ['id'])
    op.create_foreign_key('feedbacks_tag_id_fkey', 'feedbacks', 'feedback_tags', ['tag_id'], ['id'])
    op.drop_column('feedbacks', 'ai_summary')
    op.drop_column('feedbacks', 'category_type')
    op.drop_column('feedbacks', 'group_type')
    op.add_column('feedback_tags', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('feedback_tags', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_foreign_key('feedback_tags_category_id_fkey', 'feedback_tags', 'feedback_categories', ['category_id'], ['id'])
    op.drop_constraint(None, 'feedback_tags', type_='unique')
    op.drop_column('feedback_tags', 'sub_tag_name')
    op.create_table('job_summaries',
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('overall_sentiment_label', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('overall_sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('summary_product', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary_price_schemes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary_quality', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('summary_service', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name='job_summaries_job_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', name='job_summaries_pkey')
    )
    op.create_table('feedback_categories',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='feedback_categories_pkey')
    )
    op.drop_table('feedback_tag_link')
    # ### end Alembic commands ###
