"""Init

Revision ID: 98321b6da470
Revises: 
Create Date: 2026-06-03 15:04:22.284420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98321b6da470'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('batches',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('batch_number', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'PARTIAL_SUCCESS', 'COMPLETED', 'FAILED', name='batchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_status'), 'batches', ['status'], unique=False)
    op.create_table('feedback_categories',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_dictionary',
    sa.Column('canonical_id', sa.String(length=100), nullable=False),
    sa.Column('canonical_term', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('language', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PUBLISHED', 'DRAFT', 'ARCHIVED', name='keywordstatus'), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('canonical_id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('short_code', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('allowed_resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('feedback_tags',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('tag_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['feedback_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('gcs_input_uri', sa.Text(), nullable=False),
    sa.Column('gcs_stt_output_uri', sa.Text(), nullable=True),
    sa.Column('batch_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'BATCHED', 'STT_SUBMITTED', 'STT_COMPLETED', 'TRANSLATING', 'TRANSLATED', 'PROCESSING', 'NORMALIZED', 'INSIGHTS', 'COMPLETED', 'ERROR', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('stt_operation_name', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_batch_id'), 'jobs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_jobs_created_at'), 'jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('feedbacks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('tag_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('verbatim_quote', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=50), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('contractor_profile', sa.String(length=200), nullable=True),
    sa.Column('speaker_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['feedback_categories.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['feedback_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_job_id'), 'feedbacks', ['job_id'], unique=False)
    op.create_table('file_details',
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('file_extension', sa.String(length=20), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('division', sa.String(length=100), nullable=True),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('cluster', sa.String(length=100), nullable=True),
    sa.Column('rbdm_cluster', sa.String(length=100), nullable=True),
    sa.Column('town_city', sa.String(length=100), nullable=True),
    sa.Column('tsi_territory_code', sa.String(length=100), nullable=True),
    sa.Column('fme_code', sa.String(length=100), nullable=True),
    sa.Column('tty_code', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('user_type', sa.String(length=100), nullable=True),
    sa.Column('data_source', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_file_details_cluster'), 'file_details', ['cluster'], unique=False)
    op.create_index(op.f('ix_file_details_data_source'), 'file_details', ['data_source'], unique=False)
    op.create_index(op.f('ix_file_details_division'), 'file_details', ['division'], unique=False)
    op.create_index(op.f('ix_file_details_fme_code'), 'file_details', ['fme_code'], unique=False)
    op.create_index(op.f('ix_file_details_rbdm_cluster'), 'file_details', ['rbdm_cluster'], unique=False)
    op.create_index(op.f('ix_file_details_town_city'), 'file_details', ['town_city'], unique=False)
    op.create_index(op.f('ix_file_details_tsi_territory_code'), 'file_details', ['tsi_territory_code'], unique=False)
    op.create_index(op.f('ix_file_details_tty_code'), 'file_details', ['tty_code'], unique=False)
    op.create_index(op.f('ix_file_details_user_id'), 'file_details', ['user_id'], unique=False)
    op.create_index(op.f('ix_file_details_user_type'), 'file_details', ['user_type'], unique=False)
    op.create_index(op.f('ix_file_details_zone'), 'file_details', ['zone'], unique=False)
    op.create_table('job_summaries',
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('overall_sentiment_label', sa.String(length=50), nullable=True),
    sa.Column('overall_sentiment_score', sa.Float(), nullable=True),
    sa.Column('summary_product', sa.Text(), nullable=True),
    sa.Column('summary_price_schemes', sa.Text(), nullable=True),
    sa.Column('summary_quality', sa.Text(), nullable=True),
    sa.Column('summary_service', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('processed_file',
    sa.Column('job_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('gcs_transcript_uri', sa.Text(), nullable=True),
    sa.Column('raw_transcript_text', sa.Text(), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('feedback_competitors',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('feedback_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('competitor_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_competitors_feedback_id'), 'feedback_competitors', ['feedback_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedback_competitors_feedback_id'), table_name='feedback_competitors')
    op.drop_table('feedback_competitors')
    op.drop_table('processed_file')
    op.drop_table('job_summaries')
    op.drop_index(op.f('ix_file_details_zone'), table_name='file_details')
    op.drop_index(op.f('ix_file_details_user_type'), table_name='file_details')
    op.drop_index(op.f('ix_file_details_user_id'), table_name='file_details')
    op.drop_index(op.f('ix_file_details_tty_code'), table_name='file_details')
    op.drop_index(op.f('ix_file_details_tsi_territory_code'), table_name='file_details')
    op.drop_index(op.f('ix_file_details_town_city'), table_name='file_details')
    op.drop_index(op.f('ix_file_details_rbdm_cluster'), table_name='file_details')
    op.drop_index(op.f('ix_file_details_fme_code'), table_name='file_details')
    op.drop_index(op.f('ix_file_details_division'), table_name='file_details')
    op.drop_index(op.f('ix_file_details_data_source'), table_name='file_details')
    op.drop_index(op.f('ix_file_details_cluster'), table_name='file_details')
    op.drop_table('file_details')
    op.drop_index(op.f('ix_feedbacks_job_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_created_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_batch_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_table('feedback_tags')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('keyword_dictionary')
    op.drop_table('feedback_categories')
    op.drop_index(op.f('ix_batches_status'), table_name='batches')
    op.drop_table('batches')
    op.drop_table('app_config')
    # ### end Alembic commands ###
