"""add description group and category to feedback_tags

Revision ID: 9c9c9826e966
Revises: c8f45bec9079
Create Date: 2026-07-22 14:45:50.762502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c9c9826e966'
down_revision: Union[str, None] = 'c8f45bec9079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback_tags', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('feedback_tags', sa.Column('group_type', sa.String(length=100), nullable=True))
    op.add_column('feedback_tags', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feedback_tags', 'category')
    op.drop_column('feedback_tags', 'group_type')
    op.drop_column('feedback_tags', 'description')
    # ### end Alembic commands ###
