"""Manual drop of feedback_categories

Revision ID: a902fbcdb69e
Revises: bb8dc02ce655
Create Date: 2026-07-28 15:06:51.338210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a902fbcdb69e'
down_revision: Union[str, None] = 'bb8dc02ce655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE feedback_tags DROP COLUMN IF EXISTS category_id CASCADE")
    
    # Also check if feedbacks table still has the FK
    op.execute("ALTER TABLE feedbacks DROP COLUMN IF EXISTS category_id CASCADE")
        
    op.execute("DROP TABLE IF EXISTS feedback_categories CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
