"""Sync AI Pipeline models

Revision ID: bb8dc02ce655
Revises: 5e4191dfb1b3
Create Date: 2026-07-28 12:44:43.756782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8dc02ce655'
down_revision: Union[str, None] = '5e4191dfb1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
