"""Add product categories and brands

Revision ID: c25e8eb82568
Revises: 4f9ea1944e26
Create Date: 2026-07-20 13:12:39.376296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c25e8eb82568'
down_revision: Union[str, None] = '4f9ea1944e26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('product_brands',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('category_id', sa.UUID(as_uuid=False), nullable=False))
    op.add_column('products', sa.Column('brand_id', sa.UUID(as_uuid=False), nullable=False))
    op.create_foreign_key(None, 'products', 'product_brands', ['brand_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'product_categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.drop_column('products', 'category')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'brand_id')
    op.drop_column('products', 'category_id')
    op.drop_column('products', 'description')
    op.drop_table('product_brands')
    op.drop_table('product_categories')
    # ### end Alembic commands ###
