"""add_product_name_to_feedbacks

Revision ID: c5f73497ace3
Revises: 244b9d77cc00
Create Date: 2026-07-21 11:20:19.723830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f73497ace3'
down_revision: Union[str, None] = '244b9d77cc00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedbacks', sa.Column('product_name', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_feedbacks_product_name'), 'feedbacks', ['product_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feedbacks_product_name'), table_name='feedbacks')
    op.drop_column('feedbacks', 'product_name')
    # ### end Alembic commands ###
